### ISSUE TITLE
[Linux Build] libcurl.so is a symlink instead of being a file in linux_x86_64_releasedbg.zip

### ISSUE THREAD

**Issue by Elanis** [DigitalPulseSoftware/ThisSpaceOfMine#12]

**Comment by Elanis** [comment]
https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/commit/691cad51fd988241c02a2ba2e58d96cea9e29ff6

**Comment by Elanis** [comment]
libcurl is now present, but .a shouldn't be here

**Comment by SirLynix** [comment]
Should be fixed by https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/commit/81596d5638a4ca788669a2e3c7e8cdd4e223655c

**Comment by Elanis** [comment]
Fixed by https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/commit/81596d5638a4ca788669a2e3c7e8cdd4e223655c indeed
