### ISSUE TITLE
Installation faild Nazara on Mac M2

### ISSUE THREAD

**Issue by CYPT71** [DigitalPulseSoftware/ThisSpaceOfMine#14]
Before this was working !! 

<img width="1512" alt="Screenshot 2024-02-26 at 18 07 15" src="https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/assets/51490865/f4003eb4-2180-42eb-bad0-949f078e4359">

**Comment by SirLynix** [comment]
As I said on Discord, that's because of an older nzsl package, reinstall it:
```
xrepo remove --all --yes nzsl
xmake config --check
```

**Comment by SirLynix** [comment]
Closed for inactivity.
