### ISSUE TITLE
Chat display time

### ISSUE THREAD

**Issue by HelmaMalrik** [DigitalPulseSoftware/ThisSpaceOfMine#23]
I think it would be interesting to do what Minecraft does for chat : delete messages after a certain amount of time. This would also free up screen space. Have a nice day!

**Comment by SirLynix** [comment]
Implemented on dev.

Check https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/wiki/How-to-test-nightly-builds to test the nightly version.

**Comment by SirLynix** [comment]
Implemented in 0.6.2
