### ISSUE TITLE
[Quality of life] Make the "forward" key more natural when flying

### ISSUE THREAD

**Issue by Elanis** [DigitalPulseSoftware/ThisSpaceOfMine#28]
When flying, pressing Z (or W on the QWERTY keyboard) should not move us on the world related axis, but rather in front of the player camera.
This is important when facing the ground, but even more when you're on the edge of a face where it's very difficult to navigate otherwise.

**Comment by SirLynix** [comment]
Implemented on dev

**Comment by SirLynix** [comment]
Check https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/wiki/How-to-test-nightly-builds to test the nightly version.

**Comment by SirLynix** [comment]
Done in 0.5.1 (now live)

**Comment by Elanis** [comment]
Perfect, thanks ❤️

**Comment by SirLynix** [comment]
I wonder if moving up and down shouldn't stick to the old behavior though, making them relative to gravity instead of orientation

**Comment by Elanis** [comment]
Sounds better yep! 👍

**Comment by SirLynix** [comment]
Implemented on dev
