### ISSUE TITLE
Compilation Error on Linux x86_64

### ISSUE THREAD

**Issue by silverlays** [DigitalPulseSoftware/ThisSpaceOfMine#4]
while compiling with xmake, i've got this :
```
  => install nazaraengine 2023.08.09 .. ok
Failed to retrieve git data: fatal: Aucun nom trouvé, impossible de décrire quoi que ce soit.
```
and then when launching :
`./ThisSpaceOfMine: error while loading shared libraries: libNazaraWidgets.so: cannot open shared object file: No such file or directory`

Hope this helps. cheers.

**Comment by SirLynix** [comment]
Thanks for the issue!

You should use `xmake run TSOMGame`, as it will setup the environment to find all dependencies.

Also the test server is currently offline, you can start a local one using `xmake run TSOMServer` in a separate shell.

**Comment by silverlays** [comment]
indeed, launching with "xmake run" is much better :laughing:  (my apologies), but I've got 2 other problems as a result.

Server: 
```
TSOM 0.0.1 main (unknown-commit) - 2023-08-09 20:23:57
Initializing Core...
Initializing JoltPhysics3D...
Initializing Network...
Error: failed to install interruption signal handlers (build_ae96d7a4/.gens/NazaraCore/linux/unity_build/../../../../../src/Nazara/Core/SignalHandlerAppComponent.cpp:61: void Nz::SignalHandlerAppComponent::InstallSignalHandler())
```

Client:
```
TSOM 0.0.1 main (unknown-commit) - 2023-08-09 20:23:57
Initializing Core...
Initializing Utility...
Initializing Platform...
Initializing Renderer...
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
Error: Vulkan log: [Error][General][0:../src/nouveau/vulkan/nvk_physical_device.c:699]: VK_ERROR_INCOMPATIBLE_DRIVER (build_ae96d7a4/.gens/NazaraVulkanRenderer/linux/unity_build/../../../../../src/Nazara/VulkanRenderer/Wrapper/Instance.cpp:71: VkBool32 Nz::Vk::{anonymous}::DebugMessengerCallback(VkDebugUtilsMessageSeverityFlagBitsEXT, VkDebugUtilsMessageTypeFlagsEXT, const VkDebugUtilsMessengerCallbackDataEXT*, void*))
Initialized: Vulkan module
Initializing Graphics...
Vulkan log: [Info][General][0:Loader Message]: Loading layer library libVkLayer_MESA_device_select.so
Vulkan log: [Info][General][0:Loader Message]: Failed to find vkGetDeviceProcAddr in layer libVkLayer_MESA_device_select.so
Initializing JoltPhysics3D...
Initializing Network...
Initializing Widgets...
error: execv(/home/silv3r/Téléchargements/ThisSpaceOfMine/bin/linux_x86_64_release/ThisSpaceOfMine ) failed(-1)
```

ps: I'm Silv3r from twitch but i wrote in english for internationalization

**Comment by SirLynix** [comment]
The server message is not an issue.

As for the client it seems the Vulkan backend fails to initialize, you can try to use the OpenGL renderer instead: `xmake run TSOMGame --renderer-api=opengl`

**Comment by silverlays** [comment]
I've got exactly the same result
![Capture d’écran du 2023-08-12 17-45-35](https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/assets/17464661/a7298840-928a-45ec-8c79-d2e610ee99f0)

**Comment by silverlays** [comment]
I've done the following commands:
```
xmake repo -u
xmake f --check
xmake run TSOMGame --renderer-api=opengl
```
Same result

**Comment by silverlays** [comment]
with the good com
![Capture d’écran du 2023-08-12 18-10-28](https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/assets/17464661/d88c20bf-6b74-4dac-989c-224adeb096dc)
mand ( :p )

**Comment by silverlays** [comment]
Last update with the assets at the right place
![Capture d’écran du 2023-08-13 18-42-52](https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/assets/17464661/53503467-ec91-4b0f-bc3c-6ecf760f0ae2)

Console:
```
TSOM 0.0.1 main (unknown-commit) - 2023-08-12 18:18:52
Initializing Core...
Initializing Utility...
Initializing Platform...
Initializing Renderer...
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
Error: Vulkan log: [Error][General][0:../src/nouveau/vulkan/nvk_physical_device.c:699]: VK_ERROR_INCOMPATIBLE_DRIVER (build_bad7e4c1/.gens/NazaraVulkanRenderer/linux/unity_build/../../../../../src/Nazara/VulkanRenderer/Wrapper/Instance.cpp:71: VkBool32 Nz::Vk::{anonymous}::DebugMessengerCallback(VkDebugUtilsMessageSeverityFlagBitsEXT, VkDebugUtilsMessageTypeFlagsEXT, const VkDebugUtilsMessengerCallbackDataEXT*, void*))
Initialized: Vulkan module
Initializing Graphics...
Vulkan log: [Info][General][0:Loader Message]: Loading layer library libVkLayer_MESA_device_select.so
Vulkan log: [Info][General][0:Loader Message]: Failed to find vkGetDeviceProcAddr in layer libVkLayer_MESA_device_select.so
Initializing JoltPhysics3D...
Initializing Network...
Initializing Widgets...
```

**Comment by SirLynix** [comment]
This should have been fixed, could you test it again?

**Comment by silverlays** [comment]
Do you have a link for the assets please? I accidentally deleted my folder.

**Comment by silverlays** [comment]
![Capture d’écran du 2023-09-08 15-06-50](https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/assets/17464661/0d623a50-8fc9-46e7-8d5d-ab6309151762)

Everything works, good job ! :relaxed: 

In addition, one little remark: When I use the release available on github, I cannot launch the server because `./ThisServerOfMine: error while loading shared libraries: libNazaraUtility.so: cannot open shared object file: No such file or directory` (minor bug)

But after cloning the repo and building it with xmake (and putted the Assets at thre right place), everything is fine now, either on vulkan or opengl.

And to finish, don't forget that the vulkan error maybe comes from my side, but not the GL one.

Cya :wave:

**Comment by SirLynix** [comment]
> In addition, one little remark: When I use the release available on github, I cannot launch the server because ./ThisServerOfMine: error while loading shared libraries: libNazaraUtility.so: cannot open shared object file: No such file or directory (minor bug)

I though I fixed that with the rpath commit, I'll look into it.

Thanks a lot!
