### ISSUE TITLE
MacOS Build

### ISSUE THREAD

**Issue by CYPT71** [DigitalPulseSoftware/ThisSpaceOfMine#6]
No error when I build the entire project. 

But when I try to run it I get this with all dependencies installed : 

dev@[user]-mbp ThisSpaceOfMine % xmake run
TSOM 0.0.1 dev (unknown-commit) - 2023-10-03 11:06:24
Initializing Core...
Initializing Utility...
Initializing Platform...
Initializing Renderer...
Error: failed to open vulkan library (build_25a6cdd2/.gens/NazaraVulkanRenderer/macosx/unity_build/../../../../../src/Nazara/VulkanRenderer/Wrapper/Loader.cpp:133: static bool Nz::Vk::Loader::Initialize())
Error: failed to load Vulkan API, it may be not installed on your system (build_25a6cdd2/.gens/NazaraVulkanRenderer/macosx/unity_build/../../../../../src/Nazara/VulkanRenderer/Vulkan.cpp:137: static bool Nz::Vulkan::Initialize(UInt32, RenderAPIValidationLevel, const ParameterList &))
Error: Failed to create renderer implementation (build_25a6cdd2/.gens/NazaraRenderer/macosx/unity_build/../../../../../src/Nazara/Renderer/Renderer.cpp:192: void Nz::Renderer::LoadBackend(const Config &))
Error: Failed to initialize OpenGL loader (build_25a6cdd2/.gens/NazaraOpenGLRenderer/macosx/unity_build/../../../../../src/Nazara/OpenGLRenderer/OpenGLRenderer.cpp:53: virtual bool Nz::OpenGLRenderer::Prepare(const Renderer::Config &))
Error: Failed to create renderer implementation (build_25a6cdd2/.gens/NazaraRenderer/macosx/unity_build/../../../../../src/Nazara/Renderer/Renderer.cpp:192: void Nz::Renderer::LoadBackend(const Config &))
Uninitialized Renderer
Uninitialized Platform
Uninitialized Utility
Uninitialized Core
unhandled exception: no renderer found
libc++abi: terminating due to uncaught exception of type std::runtime_error: no renderer found
error: execv(/Users/dev/ThisSpaceOfMine/bin/macosx_arm64_release/ThisSpaceOfMine ) failed(-1)

When I rebuild it I get a tag error : 
dev@[user]-mbp ThisSpaceOfMine % xmake build -vD
Failed to retrieve git data: fatal: No tags can describe 'db45ac64eba0f09541d583db47fb0357074cc152'.
Try --always, or create some tags.

build cache stats:
cache directory: build/.build_cache
cache hit rate: 0%
cache hit: 0
cache miss: 0
new cached files: 0
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0

[100%]: build ok, spent 0.038s
dev@[user]-mbp ThisSpaceOfMine %

**Comment by SirLynix** [comment]
It should be better now, all libraries are bundled in the .zip

**Comment by SirLynix** [comment]
Closed for inactivity, the macOS build seems good now.
