### ISSUE TITLE
Widgets not scalings

### ISSUE THREAD

**Issue by Kbz-8** [DigitalPulseSoftware/ThisSpaceOfMine#8]
When resizing the window in the pause menu the buttons do not scale and disappear

When increasing window size :
![image](https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/assets/71275324/8d89cca9-4b9c-4bb7-a321-b2404a920e48)
![image](https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/assets/71275324/7c8708c9-64f6-495d-8d1b-b29ee5c4f486)

When decreasing window size :
![image](https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/assets/71275324/af53293d-1620-4e10-9b76-f127b9709d3a)

TSOM version : 0.2.2
OS : ArchLinux - Wayland

[Maybe unuseful infos]
Renderer Backend : Vulkan
Graphics Card : Nvidia GTX 1070
Drivers : Proprietary 545.29.06

**Comment by SirLynix** [comment]
This should be fixed now on the dev branch (https://github.com/DigitalPulseSoftware/ThisSpaceOfMine/releases/tag/0.0.0-nightly)

**Comment by Kbz-8** [comment]
seems to be fixed on the 0.3
